version: 0.2

phases:
  install:
    runtime-version:
      nodejs: 14
  pre_build:
    commands:
      - cd client
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: client/build