version: 0.2

env:
  variables:
    REACT_APP_API_URL: "api.jaemin.click"

phases:
  pre_build:
    commands:
      - cd client
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: client/build